apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: nginx
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8" />
        <title>Hello from KinD</title>
      </head>
      <body>
        <h1>Hakuna Matata — your NGINX page is live 🎉</h1>
        <p>Served from a Kubernetes ConfigMap, running on KinD.</p>
        <p><b><span style="color: blue;">Hello from Oklahoma</span></b></p>
        <p>blah blah</p>
        <p>Now with extra noise!</p>
      </body>
    </html>
